version: '3'
services:
    apache:
        build: .docker/apache
        container_name: lolbestpick_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/lolbestpick
        depends_on:
          - php

    database:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: lolbestpick_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lolbestpick
            MYSQL_USER: lolbestpick
            MYSQL_PASSWORD: lolbestpick
    php:
        build: .docker/php
        container_name: lolbestpick_php
        volumes:
          - .:/home/wwwroot/lolbestpick
        depends_on:
          - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lolbestpick_phpmyadmin
        environment:
          PMA_HOST: database
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - database

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        container_name: lolbestpick-elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        ports:
            - "5601:5601"
