# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            types:
                champion:
                    properties:
                        reference: ~
                        name: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Champion
                        provider: ~
